# Generated by Django 4.2.2 on 2023-06-13 01:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_newsletter_email_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 13, 1, 17, 52, 365782, tzinfo=datetime.timezone.utc), verbose_name='Дата публикации'),
        ),
    ]
